development:
  adapter: postgresql
  encoding: unicode
  database: feedr_development
  host: ''
  pool: 5
  username: hahaer
  password: 
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: feedr_test
  host: ''
  pool: 5
  username: hahaer
  password: 
  timeout: 5000

