development:
  adapter: postgresql
  encoding: unicode
  database: feedr_development
  pool: 5
  username: hahaer
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: feedr_test
  pool: 5
  username: hahaer
  password:
  timeout: 5000

